<a href="https://colab.research.google.com/github/feerose111/Learning_PyTorch/blob/main/pytorch_nn_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
#create model class
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):
    super().__init__()
    self.network = nn.Sequential(
            nn.Linear(num_features, 3),
            nn.ReLU(),
            nn.Linear(3, 1),
            nn.Sigmoid()
    )


  def forward(self, features):
    return self.network(features)


In [21]:
#create dataset
features = torch.rand(10,5)

#create model
model = Model(features.shape[1])

#call model for forward pass
model(features)


tensor([[0.6120],
        [0.6045],
        [0.6066],
        [0.6524],
        [0.6073],
        [0.6087],
        [0.6217],
        [0.6270],
        [0.6373],
        [0.6132]], grad_fn=<SigmoidBackward0>)

In [17]:
#show model weight
model.linear1.weight

Parameter containing:
tensor([[ 0.2712, -0.3299,  0.2109, -0.0077, -0.0585],
        [ 0.3544,  0.0641,  0.2415, -0.1584, -0.4205],
        [ 0.2077,  0.2706, -0.4258,  0.3418, -0.0556]], requires_grad=True)

In [18]:
model.linear2.bias

Parameter containing:
tensor([0.1858], requires_grad=True)

In [12]:
!pip install torchinfo

In [22]:
from torchinfo import summary
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00