In [1]:
import torch

print(torch.__version__)


2.5.1+cu124


In [2]:
if(torch.cuda.is_available()):
    print("GPU is available")
    print(torch.cuda.get_device_name(0))
    print(torch.cuda.device_count())
else:
    print("CUDA is not available")

GPU is available
Tesla T4
1


In [3]:
#torch empty
#empty function creates memory allocation
a = torch.empty(2,3)

In [4]:
#torch type
type(a)

torch.Tensor

In [5]:
#tensor zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
#tensor ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
#tensor rand
torch.rand(2,3)

tensor([[0.6007, 0.3427, 0.0765],
        [0.5367, 0.8294, 0.7921]])

In [8]:
#tourch seed for producing random value that is not changed after runnning multiple times
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [9]:
#torch tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [10]:
#arange
print("range : ",torch.arange(0,10,2))

#using linspace for evenly spread values
print("linspace : ",torch.linspace(0,10,10))

#using eye
print("using eye:", torch.eye(5))

#using full
print("using full : ", torch.full((3,3),500))


range :  tensor([0, 2, 4, 6, 8])
linspace :  tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye: tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full :  tensor([[500, 500, 500],
        [500, 500, 500],
        [500, 500, 500]])


Tensor Shapes

In [11]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [12]:
x.shape

torch.Size([2, 3])

In [13]:
torch.empty_like(x)

tensor([[135039934901648,       130096864,       130120448],
        [      130140928,               0,       129943168]])

In [14]:
torch.zeros_like(x)



tensor([[0, 0, 0],
        [0, 0, 0]])

In [15]:

torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

Tensor datatypes

In [16]:
x.dtype

torch.int64

In [21]:
#assigning datatype
torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float32)
#torch.tensor([[1.0,2.0,3.0],[4.0,5.0,6.0]], dtype=tourch.int32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [22]:
#using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [23]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

Element wise operation


In [25]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.4440, 0.9478, 0.7445],
        [0.4892, 0.2426, 0.7003]])
tensor([[0.5277, 0.2472, 0.7909],
        [0.4235, 0.0169, 0.2209]])


In [29]:
a + b

a-b

a*b

a/b

#power
a ** b

#floor division
a // b

tensor([[ 0.,  3.,  0.],
        [ 1., 14.,  3.]])

Reduction Operation

In [31]:
e = torch.randint(size=(2,3), low=0, high=10)
e

tensor([[3, 9, 4],
        [0, 5, 7]])

In [32]:
#sum
torch.sum(e)

tensor(28)

In [33]:
#sum along column
torch.sum(e, dim=0)

tensor([ 3, 14, 11])

In [34]:
#sum along row
torch.sum(e, dim=1)

tensor([16, 12])

In [36]:
#similarly for mean
#torch.mean(e)
#mean along row
#mean along column
#median
#max and min
#for product
torch.prod(e)



tensor(0)

In [38]:
#standard deviataion
#torch.std(e)

In [39]:
#variance
#torch.var(e)


In [40]:
#argmax (tells the position of the max value)
torch.argmax(e)

tensor(1)

In [41]:
#argmin (tells the position of the min value)
torch.argmin(e)

tensor(3)

In [43]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[5, 9, 9],
        [7, 5, 9]])
tensor([[8, 9],
        [7, 9],
        [2, 6]])


In [46]:
#matrix multiplication
#torch.mm(f,g)
torch.matmul(f,g)

tensor([[121, 180],
        [109, 162]])

In [47]:
vector1 = torch.tensor([2,3])
vector2 = torch.tensor([4,5])

#dot product
torch.dot(vector1, vector2)


tensor(23)

In [48]:
print(f)

tensor([[5, 9, 9],
        [7, 5, 9]])


In [49]:
#transpose
torch.transpose(f,0,1)

tensor([[5, 7],
        [9, 5],
        [9, 9]])

In [52]:
h= torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[3., 8., 5.],
        [6., 2., 9.],
        [5., 0., 4.]])

In [53]:
#determinant
torch.det(h)

tensor(142.)

In [54]:
#inverse
torch.inverse(h)

tensor([[ 0.0563, -0.2254,  0.4366],
        [ 0.1479, -0.0915,  0.0211],
        [-0.0704,  0.2817, -0.2958]])

In [55]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.9141, 0.7668, 0.1659],
        [0.4393, 0.2243, 0.8935]])
tensor([[0.0497, 0.1780, 0.3011],
        [0.1893, 0.9186, 0.2131]])


In [57]:
m.add_(n)

tensor([[0.9638, 0.9448, 0.4670],
        [0.6286, 1.1429, 1.1066]])

underscore "_" is used to perform inplace operations

In [58]:
n

tensor([[0.0497, 0.1780, 0.3011],
        [0.1893, 0.9186, 0.2131]])

In [59]:
m

tensor([[0.9638, 0.9448, 0.4670],
        [0.6286, 1.1429, 1.1066]])

Copying a tensor

In [60]:
a = torch.rand(2,3)
a

tensor([[0.3957, 0.6017, 0.4234],
        [0.5224, 0.4175, 0.0340]])

In [61]:
b = a.clone()


tensor([[0.3957, 0.6017, 0.4234],
        [0.5224, 0.4175, 0.0340]])

In [63]:
id(a)

135035083109776

In [64]:
id(b)

135035012374768

Tensor operation o GPU

In [65]:
torch.cuda.is_available()

True

In [66]:
device = torch.device('cuda')

In [67]:
#creating a tensor on GPU
torch.rand((2,3), device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [68]:
#moving an existing tensor on gpu
a

tensor([[0.3957, 0.6017, 0.4234],
        [0.5224, 0.4175, 0.0340]])

In [70]:
b = a.to(device)

In [72]:
b + 5

tensor([[5.3957, 5.6017, 5.4234],
        [5.5224, 5.4175, 5.0340]], device='cuda:0')

Reshaping tensors

In [74]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [76]:
#rehshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [77]:
#flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [79]:
b = torch.rand(2,3,4)
b

tensor([[[0.8993, 0.2732, 0.3397, 0.1879],
         [0.5534, 0.2682, 0.9556, 0.9761],
         [0.5934, 0.3124, 0.9431, 0.8519]],

        [[0.9815, 0.1132, 0.4783, 0.4436],
         [0.3847, 0.4521, 0.5569, 0.9952],
         [0.0015, 0.0813, 0.4907, 0.2130]]])

In [81]:
#permute
b.permute(2,1,0).shape

torch.Size([4, 3, 2])

In [83]:
#unsqueeze

c = torch.rand(226,226,3)
c.unsqueeze(dim=1).shape


torch.Size([226, 1, 226, 3])

In [87]:
#squeeze
c.squeeze(1).shape

torch.Size([226, 226, 3])

NumPy and PyTorch

In [88]:
import numpy as np

In [89]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [90]:
b = a.numpy()

In [91]:
b

array([1, 2, 3])

In [92]:
type(b)

numpy.ndarray

In [93]:
c = np.array([2,3,4])
c

array([2, 3, 4])

In [94]:
torch.from_numpy(c)


tensor([2, 3, 4])