<a href="https://colab.research.google.com/github/feerose111/Learning_PyTorch/blob/main/training_pipeline_using_nn_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [47]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import kagglehub
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder


In [48]:
df = pd.read_csv("/content/data.csv")
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [49]:
df.shape

(569, 33)

In [50]:
df = df.drop(columns=["id", "Unnamed: 32" ])

In [51]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

Splitting the data and features into train and test data

In [52]:
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2, random_state=1)

Scaling

In [53]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [54]:
x_train

array([[ 1.0449852 ,  0.29708512,  1.01044815, ...,  1.21839781,
         0.29811854,  0.08380738],
       [ 1.68141074, -1.14098169,  1.70338066, ...,  0.69716372,
        -0.88595033, -0.41234747],
       [-1.44260855, -1.12732916, -1.4504636 , ..., -1.52233766,
         0.1807324 , -0.33657109],
       ...,
       [ 0.82638686,  1.17539807,  0.86625411, ...,  1.10638475,
         0.72853438,  3.02284824],
       [-0.05077356,  0.43133503, -0.11146165, ..., -0.54050588,
        -1.1207226 , -0.44903285],
       [-0.32748032, -0.21260945, -0.39904866, ..., -0.98109057,
        -1.52732096, -1.31985978]])

In [55]:
x_test

array([[ 0.1318529 , -1.22289689,  0.22619275, ..., -0.07497962,
        -0.09827233,  0.50779424],
       [-0.28874137, -0.15799931, -0.26406701, ...,  1.38865765,
         1.72716717,  2.06060854],
       [-0.34961686, -0.75871076, -0.3778201 , ..., -0.15264201,
         0.84251802,  0.73392057],
       ...,
       [-1.43458406, -0.46063046, -1.35313261, ...,  0.88385214,
         2.28517664,  2.03655255],
       [ 0.08757982, -0.00327061,  0.06717876, ..., -0.29691482,
        -0.70391675, -0.54164842],
       [-0.11995025, -0.81104547, -0.16833819, ..., -1.23513619,
        -1.74508076, -0.9343625 ]])

In [56]:
y_train

408    M
4      M
307    B
386    B
404    B
      ..
129    M
144    B
72     M
235    B
37     B
Name: diagnosis, Length: 455, dtype: object

Encoding the target into binary digits

In [57]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [58]:
y_train

array([1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,

converting numpy array to tourch tensors

In [59]:
x_train_tensor = torch.from_numpy(x_train).float()
X_test_tensor = torch.from_numpy(x_test).float()
y_train_tensor = torch.from_numpy(y_train).float()
y_test_tensor = torch.from_numpy(y_test).float()

In [60]:
x_train_tensor.shape


torch.Size([455, 30])

In [61]:
X_test_tensor.shape


torch.Size([114, 30])

In [62]:
print(y_train_tensor.shape)
print(y_test_tensor.shape)

torch.Size([455])
torch.Size([114])


In [63]:
x_train_tensor

tensor([[ 1.0450,  0.2971,  1.0104,  ...,  1.2184,  0.2981,  0.0838],
        [ 1.6814, -1.1410,  1.7034,  ...,  0.6972, -0.8860, -0.4123],
        [-1.4426, -1.1273, -1.4505,  ..., -1.5223,  0.1807, -0.3366],
        ...,
        [ 0.8264,  1.1754,  0.8663,  ...,  1.1064,  0.7285,  3.0228],
        [-0.0508,  0.4313, -0.1115,  ..., -0.5405, -1.1207, -0.4490],
        [-0.3275, -0.2126, -0.3990,  ..., -0.9811, -1.5273, -1.3199]])

Building a model

In [64]:
class MySimpleNN(nn.Module):

  def __init__(self , num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
     out = self.linear(features)
     out = self.sigmoid(out)
     return out


In [65]:
learning_rate=0.1
epochs = 25

In [66]:
loss_function = nn.BCELoss()

In [72]:
model = MySimpleNN(x_train_tensor.shape[1])
#define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

#define loop
for epoch in range(epochs):
  #forward pass
  y_pred = model(x_train_tensor)

  #loss calculation
  loss = loss_function(y_pred, y_train_tensor.view(-1,1))

  #clear gradient using zero grad
  optimizer.zero_grad()

  #backward pass
  loss.backward()

  #update weight and bias
  optimizer.step()


  #print loss on each epochs
  print(f"epoch {epoch + 1}:==> loss {loss}")

epoch 1:==> loss 0.7183285355567932
epoch 2:==> loss 0.5394052267074585
epoch 3:==> loss 0.44174161553382874
epoch 4:==> loss 0.3826368451118469
epoch 5:==> loss 0.3426368236541748
epoch 6:==> loss 0.3134065866470337
epoch 7:==> loss 0.29090070724487305
epoch 8:==> loss 0.2729136049747467
epoch 9:==> loss 0.25813204050064087
epoch 10:==> loss 0.24572019279003143
epoch 11:==> loss 0.23511791229248047
epoch 12:==> loss 0.2259337306022644
epoch 13:==> loss 0.21788489818572998
epoch 14:==> loss 0.2107611447572708
epoch 15:==> loss 0.20440274477005005
epoch 16:==> loss 0.19868552684783936
epoch 17:==> loss 0.19351164996623993
epoch 18:==> loss 0.188802570104599
epoch 19:==> loss 0.18449459969997406
epoch 20:==> loss 0.18053552508354187
epoch 21:==> loss 0.17688187956809998
epoch 22:==> loss 0.17349736392498016
epoch 23:==> loss 0.17035135626792908
epoch 24:==> loss 0.16741777956485748
epoch 25:==> loss 0.164674311876297


In [73]:
model.linear.bias

Parameter containing:
tensor([-0.2951], requires_grad=True)

Model Evaluation

In [74]:
with torch.no_grad():
 y_pred = model(X_test_tensor)
 y_pred = (y_pred > 0.999).float()
 accuracy = (y_pred == y_test_tensor).float().mean()
 print(f"Accuracy: {accuracy}")


Accuracy: 0.6292705535888672
